name: Improved Theme Settings
type: module
description: Makes the theme pages a bit UI friendly for people with the permissions.
# core: 8.x
package: Custom

# version: 1.0

# Information added by Drupal.org packaging script on 2017-05-18
version: '8.x-1.0-rc5'
core: '8.x'
project: 'social'
datestamp: 1495103593
